export const FETCH_ALL_FEATURES_BEGIN = "FETCH_ALL_FEATURES_BEGIN";
export const FETCH_ALL_FEATURES_SUCCESS = "FETCH_ALL_FEATURES_SUCCESS";
export const FETCH_ALL_FEATURES_ERROR = "FETCH_ALL_FEATURES_ERROR";

export const SAVE_FEATURES_BEGIN = "SAVE_FEATURES_BEGIN";
export const SAVE_FEATURES_SUCCESS = "SAVE_FEATURES_SUCCESS";
export const SAVE_FEATURES_ERROR = "SAVE_FEATURES_ERROR"

export const UPDATE_FEATURE = "UPDATE_FEATURE";
export const RESET_FEATURES = "RESET_FEATURES";